config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/atmorep-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/atmorep-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-sepia-frog.sh
        container: qc.acc_stealthy-indigo-okapi
  QC.Doc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-olivine-kangaroo.sh
        container: qc.doc_snoopy-flax-audemer
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-carmine-blue.sh
        container: qc.doc_paltry-crimson-leopard
      github.com/interTwin-eu/atmorep-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-chartreuse-duck.sh
        container: qc.doc_woozy-saffron-otter
  QC.Lic:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-eggplant-chameleon.sh
        container: qc.lic_snappy-coral-serval
  QC.Met:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-mauve-cassowary.sh
        container: qc.met_zippy-persimmon-hyrax
  QC.Sec:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-violet-quoll.sh
        container: qc.sec_thirsty-cerise-catfish
  QC.Sty:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-olive-ocelot.sh
        container: qc.sty_boozy-amaranth-wasp
      github.com/interTwin-eu/atmorep-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-russet-snail.sh
        container: qc.sty_stealthy-tomato-dugong
      github.com/interTwin-eu/atmorep-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-magenta-donkey.sh
        container: qc.sty_trippy-tomato-orangutan
  QC.Uni:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-red-stingray.sh
        container: qc.uni_sickly-taupe-robin
  QC.Ver:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-bronze-mastiff.sh
        container: qc.ver_stealthy-cardinal-coati
timeout: 5400
