config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/matbun/atmorep-itwinai-plugin:
      branch: main
      repo: https://github.com/matbun/atmorep-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/matbun/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-champagne-blue.sh
        container: qc.acc_scanty-razzmatazz-flamingo
  QC.Doc:
    repos:
      github.com/matbun/atmorep-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-indigo-meerkat.sh
        container: qc.doc_sloppy-amethyst-sponge
      github.com/matbun/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-amber-bobcat.sh
        container: qc.doc_muggy-turquoise-bordeaux
      github.com/matbun/atmorep-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-plum-dunker.sh
        container: qc.doc_nippy-champagne-bison
  QC.Lic:
    repos:
      github.com/matbun/atmorep-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-vermilion-chamois.sh
        container: qc.lic_sickly-carmine-antelope
  QC.Met:
    repos:
      github.com/matbun/atmorep-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-black-newt.sh
        container: qc.met_lovely-violet-manatee
  QC.Sec:
    repos:
      github.com/matbun/atmorep-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-tan-bison.sh
        container: qc.sec_shaggy-silver-moose
  QC.Sty:
    repos:
      github.com/matbun/atmorep-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-viridian-woodpecker.sh
        container: qc.sty_scummy-wisteria-maltese
      github.com/matbun/atmorep-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-buff-iguana.sh
        container: qc.sty_sleazy-tomato-tzu
      github.com/matbun/atmorep-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-goldenrod-husky.sh
        container: qc.sty_crabby-flax-mongrel
  QC.Uni:
    repos:
      github.com/matbun/atmorep-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-coral-skunk.sh
        container: qc.uni_goopy-peach-ibis
  QC.Ver:
    repos:
      github.com/matbun/atmorep-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ochre-urchin.sh
        container: qc.ver_sunny-lilac-dolphin
timeout: 5400
