config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/atmorep-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/atmorep-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-mustard-chin.sh
        container: qc.acc_stuffy-orange-koala
  QC.Doc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-periwinkle-rattlesnake.sh
        container: qc.doc_surly-cerulean-hippopotamus
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-sepia-tamarin.sh
        container: qc.doc_tacky-lilac-urchin
      github.com/interTwin-eu/atmorep-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cerulean-ant.sh
        container: qc.doc_goopy-chestnut-leopard
  QC.Lic:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-rose-beetle.sh
        container: qc.lic_flimsy-sangria-sparrow
  QC.Met:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-rose-slug.sh
        container: qc.met_stealthy-asparagus-woodlouse
  QC.Sec:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-platinum-squirt.sh
        container: qc.sec_skimpy-linen-moth
  QC.Sty:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-ivory-husky.sh
        container: qc.sty_thirsty-plum-deer
      github.com/interTwin-eu/atmorep-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-jade-wombat.sh
        container: qc.sty_sunny-magnolia-panda
      github.com/interTwin-eu/atmorep-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-scarlet-lemur.sh
        container: qc.sty_randy-red-mongoose
  QC.Uni:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lilac-bobcat.sh
        container: qc.uni_sleepy-cobalt-chow
  QC.Ver:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-yellow-gar.sh
        container: qc.ver_ugly-cardinal-alligator
timeout: 5400
