config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/matbun/atmorep-itwinai-plugin:
      branch: main
      repo: https://github.com/matbun/atmorep-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/matbun/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-charcoal-emu.sh
        container: qc.acc_snoopy-lime-ant
  QC.Doc:
    repos:
      github.com/matbun/atmorep-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-puce-jackal.sh
        container: qc.doc_gummy-jade-ladybird
      github.com/matbun/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cream-ant.sh
        container: qc.doc_greasy-fuchsia-skunk
      github.com/matbun/atmorep-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-ultramarine-sheep.sh
        container: qc.doc_stuffy-yellow-quetzal
  QC.Lic:
    repos:
      github.com/matbun/atmorep-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lemon-bulldog.sh
        container: qc.lic_geeky-turquoise-robin
  QC.Met:
    repos:
      github.com/matbun/atmorep-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-mauve-fish.sh
        container: qc.met_skinny-blue-olm
  QC.Sec:
    repos:
      github.com/matbun/atmorep-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-indigo-octopus.sh
        container: qc.sec_bluesy-tangerine-angora
  QC.Sty:
    repos:
      github.com/matbun/atmorep-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-pink-chow.sh
        container: qc.sty_snappy-cornflower-malamute
      github.com/matbun/atmorep-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-magnolia-hippopotamus.sh
        container: qc.sty_jumpy-green-fousek
      github.com/matbun/atmorep-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-amethyst-fish.sh
        container: qc.sty_beady-chestnut-barb
  QC.Uni:
    repos:
      github.com/matbun/atmorep-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cerise-skunk.sh
        container: qc.uni_muzzy-rose-weasel
  QC.Ver:
    repos:
      github.com/matbun/atmorep-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-olive-chipmunk.sh
        container: qc.ver_messy-seashell-molly
timeout: 5400
