config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/matbun/atmorep-itwinai-plugin:
      branch: main
      repo: https://github.com/matbun/atmorep-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/matbun/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-platinum-caracal.sh
        container: qc.acc_trippy-russet-squirt
  QC.Doc:
    repos:
      github.com/matbun/atmorep-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-chestnut-caracal.sh
        container: qc.doc_gamy-auburn-buzzard
      github.com/matbun/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-alizarin-neanderthal.sh
        container: qc.doc_blurry-beige-catfish
      github.com/matbun/atmorep-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cardinal-sheepdog.sh
        container: qc.doc_gimpy-red-chihuahua
  QC.Lic:
    repos:
      github.com/matbun/atmorep-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-black-kangaroo.sh
        container: qc.lic_woozy-coral-cuscus
  QC.Met:
    repos:
      github.com/matbun/atmorep-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-peach-lizard.sh
        container: qc.met_woolly-cinnamon-spoonbill
  QC.Sec:
    repos:
      github.com/matbun/atmorep-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-harlequin-dhole.sh
        container: qc.sec_stinky-persimmon-bear
  QC.Sty:
    repos:
      github.com/matbun/atmorep-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-plum-barracuda.sh
        container: qc.sty_blurry-amethyst-donkey
      github.com/matbun/atmorep-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-harlequin-quokka.sh
        container: qc.sty_jumpy-alizarin-cichlid
      github.com/matbun/atmorep-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-amethyst-bat.sh
        container: qc.sty_dorky-sepia-neanderthal
  QC.Uni:
    repos:
      github.com/matbun/atmorep-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.homey-linen-foxhound.sh
        container: qc.uni_droopy-flax-chihuahua
  QC.Ver:
    repos:
      github.com/matbun/atmorep-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-carmine-koala.sh
        container: qc.ver_cheeky-tangerine-okapi
timeout: 5400
