config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/atmorep-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/atmorep-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-russet-wrasse.sh
        container: qc.acc_bumpy-azure-guppy
  QC.Doc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-asparagus-chinook.sh
        container: qc.doc_skimpy-myrtle-fossa
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-bronze-booby.sh
        container: qc.doc_gummy-beige-elephant
      github.com/interTwin-eu/atmorep-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-zucchini-fossa.sh
        container: qc.doc_chewy-pear-paradise
  QC.Lic:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-asparagus-drever.sh
        container: qc.lic_gloppy-cobalt-beetle
  QC.Met:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.messy-violet-discus.sh
        container: qc.met_grumpy-xanthic-dragonfly
  QC.Sec:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-white-gorilla.sh
        container: qc.sec_clammy-yellow-wallaby
  QC.Sty:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-teal-magpie.sh
        container: qc.sty_clammy-platinum-catfish
      github.com/interTwin-eu/atmorep-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-gold-husky.sh
        container: qc.sty_crabby-sangria-gerbil
      github.com/interTwin-eu/atmorep-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lemon-kingfisher.sh
        container: qc.sty_droopy-ultramarine-lizard
  QC.Uni:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-myrtle-chipmunk.sh
        container: qc.uni_baggy-cobalt-snake
  QC.Ver:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-alizarin-chinchilla.sh
        container: qc.ver_leaky-emerald-weasel
timeout: 5400
