config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/atmorep-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/atmorep-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-maroon-affenpinscher.sh
        container: qc.acc_gimpy-silver-saola
  QC.Doc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-periwinkle-cat.sh
        container: qc.doc_craggy-bronze-bongo
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cornflower-jellyfish.sh
        container: qc.doc_pokey-linen-shark
      github.com/interTwin-eu/atmorep-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-salmon-quoll.sh
        container: qc.doc_randy-tan-birman
  QC.Lic:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-corn-shrimp.sh
        container: qc.lic_stinky-maroon-cockroach
  QC.Met:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-mauve-uguisu.sh
        container: qc.met_silly-mauve-wolverine
  QC.Sec:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-sepia-wasp.sh
        container: qc.sec_shaky-aqua-worm
  QC.Sty:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-linen-lobster.sh
        container: qc.sty_clammy-puce-tzu
      github.com/interTwin-eu/atmorep-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-tangerine-salamander.sh
        container: qc.sty_flaky-amaranth-penguin
      github.com/interTwin-eu/atmorep-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-aquamarine-vulture.sh
        container: qc.sty_lanky-black-akita
  QC.Uni:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.homey-aquamarine-chinchilla.sh
        container: qc.uni_smelly-scarlet-hedgehog
  QC.Ver:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-gamboge-gorilla.sh
        container: qc.ver_stinky-ultramarine-shrimp
timeout: 5400
