config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/atmorep-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/atmorep-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-grey-akita.sh
        container: qc.acc_randy-champagne-mayfly
  QC.Doc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-silver-stoat.sh
        container: qc.doc_woozy-charcoal-seal
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-sapphire-tang.sh
        container: qc.doc_skimpy-ecru-meerkat
      github.com/interTwin-eu/atmorep-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-amethyst-mist.sh
        container: qc.doc_chewy-linen-gerbil
  QC.Lic:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-coral-hornet.sh
        container: qc.lic_grumpy-peach-barb
  QC.Met:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-lemon-tarsier.sh
        container: qc.met_stuffy-amethyst-numbat
  QC.Sec:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-violet-tamarin.sh
        container: qc.sec_slimy-cinnamon-koala
  QC.Sty:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-green-coati.sh
        container: qc.sty_muggy-ochre-okapi
      github.com/interTwin-eu/atmorep-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-orange-mau.sh
        container: qc.sty_jumpy-lavender-leopard
      github.com/interTwin-eu/atmorep-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-chartreuse-caiman.sh
        container: qc.sty_nippy-magenta-mole
  QC.Uni:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-celadon-toucan.sh
        container: qc.uni_grumpy-platinum-vole
  QC.Ver:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-gold-gecko.sh
        container: qc.ver_sleazy-russet-bat
timeout: 5400
