config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/atmorep-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/atmorep-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-silver-octopus.sh
        container: qc.acc_slaphappy-cinnabar-rabbit
  QC.Doc:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-corn-sloth.sh
        container: qc.doc_cranky-cinnamon-barracuda
      github.com/interTwin-eu/atmorep-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-aqua-chimpanzee.sh
        container: qc.doc_sleazy-tomato-ragdoll
      github.com/interTwin-eu/atmorep-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-olive-tapir.sh
        container: qc.doc_queasy-salmon-moorhen
  QC.Lic:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-xanthic-quail.sh
        container: qc.lic_stealthy-harlequin-malamute
  QC.Met:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-asparagus-ocelot.sh
        container: qc.met_stealthy-rose-urchin
  QC.Sec:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-pumpkin-labradoodle.sh
        container: qc.sec_boozy-ruby-dodo
  QC.Sty:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-burgundy-llama.sh
        container: qc.sty_gamy-tomato-hornet
      github.com/interTwin-eu/atmorep-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-lemon-squirt.sh
        container: qc.sty_skinny-malachite-duck
      github.com/interTwin-eu/atmorep-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-peach-bison.sh
        container: qc.sty_smelly-grey-rottweiler
  QC.Uni:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-mauve-vulture.sh
        container: qc.uni_bluesy-cinnamon-bonobo
  QC.Ver:
    repos:
      github.com/interTwin-eu/atmorep-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-gold-caterpillar.sh
        container: qc.ver_bumpy-cerulean-spitz
timeout: 5400
